[project]
name = "translate-pretrain-corpus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "distilabel[openai]>=1.5.3",
    "dotenv>=0.9.9",
    "openai>=1.86.0",
]
